# -*- coding: utf-8 -*-
"""
Created on Fri Nov 27 08:29:35 2020

@author: BerndKuebrich
"""
import pygame

# TILES
DIRT = 0
GRASS = 1
WATER = 2
WALL = 3


#Dictionary linking tiles to their colors

TEXTURES = {
    DIRT: pygame.image.load('Level/ground.png'),
    GRASS: pygame.image.load('Level/grass.png'),
    WATER: pygame.image.load('Level/water.png'),
    WALL: pygame.image.load('Level/wall.png'),
}

#Tiles to be displayed
MAP1= [
   [GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WATER, WATER, WATER],
   [GRASS, GRASS, GRASS, GRASS, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, GRASS, GRASS, WATER, WATER, WATER, WATER, WATER],
   [GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, DIRT, DIRT, DIRT, DIRT, GRASS, GRASS, GRASS, GRASS, GRASS, WATER, WATER, WATER, GRASS, GRASS],
   [GRASS, GRASS, GRASS, GRASS, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, GRASS, GRASS, GRASS, WATER, WATER, WATER, WATER, GRASS, GRASS, GRASS],
   [GRASS, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, GRASS, GRASS, GRASS, WATER, WATER, GRASS, GRASS, GRASS, GRASS, GRASS],
   [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, WATER, WATER, WATER, WATER, GRASS, GRASS, GRASS],
   [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, WATER, WATER, WATER, WATER, WATER, WATER, WATER, GRASS, GRASS],
   [GRASS, GRASS, GRASS, GRASS, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, WATER, WATER, WATER, WATER, WATER, WATER, GRASS, GRASS, GRASS],
   [GRASS, GRASS, GRASS, GRASS, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, WATER, WATER, WATER, WATER, WATER, WATER, WATER, GRASS, GRASS],
   [GRASS, GRASS, GRASS, GRASS, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER, GRASS]
]

#Game dimensions
TILESIZE = 70
MAPWIDTH = 20
MAPHEIGHT = 10

pygame.init()
pygame.display.set_caption("An unexpected Journey") #Name im Screenhead
#MAPHEIGHT
DISPLAYSURFACE = pygame.display.set_mode((MAPWIDTH*TILESIZE, MAPHEIGHT*TILESIZE))

#COLORS
WHITE = (200,200,200)
BLACK = (0,0,0)
BLUE = (30,144,255)
GREEN = (60,179,113)
RED = (178,0,0)